BI-2288 - GitHub Improvements
Breeding-Insight/bi-docker-stack pull request #54
Opened 2024-12-03 01:24 UTC by mlm483

I added architecture info and DeltaBreed branding to README.md.

2024-12-11 21:35 UTC, HMS17 approved these changes

2025-01-08 16:38 UTC, dmeidlin requested changes
In the architecture diagram, the BrAPI arrow between Fieldbook and BI-API needs to be reversed to be consistent with the other two arrows for BI-WEB and `breedinginsight.net/brapi/v2`, implying that all three arrows represent requests/responses in which BI-API is the server and the others are clients.

2025-01-09 16:57 UTC, mlm483 commented
> In the architecture diagram, the BrAPI arrow between Fieldbook and BI-API needs to be reversed to be consistent with the other two arrows for BI-WEB and `breedinginsight.net/brapi/v2`, implying that all three arrows represent requests/responses in which BI-API is the server and the others are clients.

@dmeidlin  I updated the diagram to make it clear that Field Book is the client and bi-api is the server.

2025-01-10 22:37 UTC, dmeidlin approved these changes

2025-01-13 15:07 UTC, merged